title: Computational Astrophysics
author: J. J. Zanazzi
email: "jxz224@psu.edu"

description: >
  Astro 410 course in the Dept. of Astronomy and Astrophysics at Penn State.

theme: minima

header_pages:
  - syllabus.md
  - project.md
  - lectures.md
  - homeworks.md
  - tips.md
