title: Astro 410

description: >
  Computational Astrophysics course taught by Prof. J. J. Zanazzi, at the Dept. of Astronomy and Astrophysics at Penn State

theme: minima

header_pages:
  - syllabus.md
  - project.md
